name: Deploy Laravel Inertia App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass rsync

    - name: Deploy Application via SSH Password
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
        --exclude='.git*' \
        --exclude='.env' \
        --exclude='node_modules' \
        --exclude='vendor' \
        ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/your/app

    - name: SSH into Server and Finish Deployment
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /path/to/your/app
        composer install --optimize-autoloader --no-dev
        npm install
        npm run build
        php artisan migrate:fresh --seed --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        EOF
