name: Deploy

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Debug Secrets
        run: |
          echo "REMOTE_HOST: $REMOTE_HOST"
          echo "REMOTE_USER: $REMOTE_USER"
          echo "REMOTE_PORT: $REMOTE_PORT"

      - name: Synchronize Files to Server
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "public/build/"
          TARGET: "/domains/cortexitsolution.com/public_html/measypro/public/build/"
          ARGS: "-rltgoDzvO --delete" # Use Rsync args to handle the sync process

      - name: Run Remote Artisan Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }} # Corrected spelling here
          script: |
            cd domains
            cd cortexitsolution.com
            cd public_html
            cd measypro
            php artisan migrate:fresh --seed
            php artisan optimize
